# Generated by Django 4.2 on 2026-08-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('vacunacion', models.CharField(choices=[('al_dia', 'Al día'), ('pendiente', 'Pendiente'), ('alergia', 'Alergia')], max_length=20)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
